<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_RAY100129</name>
   <tag></tag>
   <elementGuidId>e0598cc0-a60f-4e9b-9af2-e8e1830b1185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:void(0);' and (text() = 'RAY100129' or . = 'RAY100129')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;gotoAssetsDetail('272fdc06-f268-4d5c-bb8c-c30ad057472e')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>342973b9-e21c-4aa4-8dd8-20e1eaaa53b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>03e1c29e-af63-4f6f-ac6a-c59d60c7f8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gotoAssetsDetail('272fdc06-f268-4d5c-bb8c-c30ad057472e')</value>
      <webElementGuid>370e35ec-3811-400c-8cf3-cad2456164bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RAY100129</value>
      <webElementGuid>86715e24-8885-4ce6-9ab3-be7201ba2bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewAssets_table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[1]</value>
      <webElementGuid>e76e49f6-bef0-4838-b9c9-369c43459cb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;gotoAssetsDetail('272fdc06-f268-4d5c-bb8c-c30ad057472e')&quot;]</value>
      <webElementGuid>961aafab-42ce-44b1-9de7-a525fd5b2701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='viewAssets_table']/tbody/tr/td[2]/a</value>
      <webElementGuid>14fbdf6f-07d4-4853-8575-020dd91b7ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'RAY100129')]</value>
      <webElementGuid>fa156978-4b62-46b8-b3e5-4b59bd26107f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::a[1]</value>
      <webElementGuid>0eafa0bd-4572-4b0f-bb46-b052243e2ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::a[1]</value>
      <webElementGuid>61f17b30-104c-4701-9bdc-b60eb38cc9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAY100129'])[2]/preceding::a[1]</value>
      <webElementGuid>df9bac06-6519-4b42-8858-206bf85f24d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer equipment'])[1]/preceding::a[2]</value>
      <webElementGuid>ae11bd30-eac1-49e7-9790-800060459f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RAY100129']/parent::*</value>
      <webElementGuid>922c2a61-8b65-4c91-a392-9d71d16fa37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>37f8e1df-3f7c-46a6-8bd8-8e5b223e8242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>3ee396d1-8c15-4c30-8e4c-981d727644c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'RAY100129' or . = 'RAY100129')]</value>
      <webElementGuid>ae10eb81-426d-459e-af84-370343299e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
