<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You have successfully added an asset</name>
   <tag></tag>
   <elementGuidId>ec4c09b4-d406-4074-b786-ac689db96e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vprn06u']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dad0207c-947e-4343-8706-2d70f80eca47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You have successfully added an asset</value>
      <webElementGuid>05c30953-b010-45b3-9507-623f1609c76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vprn06u&quot;)/div[@class=&quot;Toastify__toast-body&quot;]/div[2]</value>
      <webElementGuid>6875cf17-4c74-4358-b6ae-317fde832a52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vprn06u']/div/div[2]</value>
      <webElementGuid>9e27a018-681f-4067-b3c2-cd7a5fadfed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/preceding::div[6]</value>
      <webElementGuid>1663c4e5-7d97-4dfc-98df-3e38e395b67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Assets'])[1]/preceding::div[7]</value>
      <webElementGuid>446b988a-5486-4b8c-b6bc-25a1d89ed9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You have successfully added an asset']/parent::*</value>
      <webElementGuid>76f4b8e2-0683-47bd-91bc-6908b5e77d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]</value>
      <webElementGuid>22c44ed1-919e-4f32-b915-709b2c4f3805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'You have successfully added an asset' or . = 'You have successfully added an asset')]</value>
      <webElementGuid>67b81ace-46c3-4e3c-931a-1bc329e9bbae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
