<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Drop Asset file here to import assets</name>
   <tag></tag>
   <elementGuidId>3596fae6-701a-43bd-a244-a3708eb93d0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropzone-asset</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='dropzone-asset']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>7b434dca-38e2-4952-8b6c-d72404c32665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>/upload</value>
      <webElementGuid>185d1fe3-7e24-452b-b148-eb1741775a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropzone form-control h-25 dz-clickable</value>
      <webElementGuid>2ad3875a-8eae-46a3-a1a7-11feaf1b9b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropzone-asset</value>
      <webElementGuid>0768ca4f-e907-4041-91ea-afd95b45e829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enctype</name>
      <type>Main</type>
      <value>multipart/form-data</value>
      <webElementGuid>a1086b1e-8578-4a1c-baa3-ee6053425da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drop Asset file here to import assets.</value>
      <webElementGuid>fad99f3f-5d08-4b6e-9a9d-3d56bee59746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropzone-asset&quot;)</value>
      <webElementGuid>b26280bd-00ea-4083-a29c-72c6bf4e624a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='dropzone-asset']</value>
      <webElementGuid>5118b2ca-825d-4218-9a6d-fa9b6c7344c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/div/form</value>
      <webElementGuid>acd4c92e-5f8a-46ae-948c-d146e5fe912a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Asset'])[1]/following::form[1]</value>
      <webElementGuid>79e0c116-1ffc-417a-944f-b740995c6a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::form[1]</value>
      <webElementGuid>fb86630f-6305-4b57-b4e8-7c1c977d1c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import Asset'])[1]/preceding::form[1]</value>
      <webElementGuid>31f8611d-99c7-48f9-af4d-7755a551d494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>3dddf1af-6e19-4db6-b848-e2a5f8a21df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'dropzone-asset' and (text() = 'Drop Asset file here to import assets.' or . = 'Drop Asset file here to import assets.')]</value>
      <webElementGuid>319ac1c6-48c6-4e28-82e9-1a4d99ee5d49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
