<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cancel_smallModal</name>
   <tag></tag>
   <elementGuidId>81b72a88-dd76-415b-ba85-684de5d9cbb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#smallModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='smallModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2abec10c-de88-405c-bdad-f180d79c2885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>smallModal</value>
      <webElementGuid>5849d6a6-9c90-448d-8d24-2e8bcc8d5d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn ml-2</value>
      <webElementGuid>620fd036-8870-45a3-a089-80ec6843eb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8b52b011-6d4b-41be-84b7-fe59646a52ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>825a32df-0554-416a-a9d5-fc5e1d76a476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;smallModal&quot;)</value>
      <webElementGuid>11c0581c-09e6-4cca-8031-abdfd1e1c2f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='smallModal']</value>
      <webElementGuid>79a7338d-54bd-4d1e-89c9-afcbe76f82f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[18]/input</value>
      <webElementGuid>e274f8f4-a2a5-4481-8d17-62b1a11c212c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/input</value>
      <webElementGuid>a93899f6-7ef5-4763-b1f9-1039dd6e3c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'smallModal' and @type = 'submit']</value>
      <webElementGuid>e36ef080-1215-458b-879f-d93ba2906a4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
