<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial Number_serial_number</name>
   <tag></tag>
   <elementGuidId>fae2163d-1f1f-48b4-9a9b-24e2247857c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#serial_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='serial_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60f41a74-f491-4850-b4aa-77bc7a4711f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a3e2027-bd32-4ba4-8b02-9ad58167e8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serial_number</value>
      <webElementGuid>cf93327f-9770-4af5-bd1d-772bf2245dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serial_number</value>
      <webElementGuid>493dc698-247f-45b1-8886-2fea1b908949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9cfeecd8-5853-41ab-876b-9906e304e103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter serial number</value>
      <webElementGuid>c7f31f00-bbc3-44ed-a5d8-643ce7519170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serial_number&quot;)</value>
      <webElementGuid>0973cfea-b46e-4ace-bd0d-dc7cb8ca00ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='serial_number']</value>
      <webElementGuid>8fa27126-1f5b-4246-9a83-3d5d9e557b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>a8199f92-7d99-42dc-bcf4-6b72a8e23eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>b54ac6f7-cf8c-4136-af95-34f830548973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'serial_number' and @id = 'serial_number' and @placeholder = 'Enter serial number']</value>
      <webElementGuid>d4099380-5c5f-4dba-9039-236f29d78a8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
