<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Purchase Date_purchase_date</name>
   <tag></tag>
   <elementGuidId>9b3d9e71-16e5-4258-b5c0-1e39af6e24ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#purchase_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='purchase_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>478008f9-7f7f-40e8-9a4f-a5ef7d849fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>2ff2cef7-d918-456f-8989-ce55f79d644b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purchase_date</value>
      <webElementGuid>9ab2e05c-d135-4449-b51a-19d629692c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchase_date</value>
      <webElementGuid>17af09cc-e5ea-44bd-89bc-1e566a0e9df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b55eca40-f1f5-48b9-9385-61d23390d278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2023-07-13</value>
      <webElementGuid>2c896f70-1699-4e36-8b47-bdc7bce0744a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchase_date&quot;)</value>
      <webElementGuid>3f275903-190a-499c-b593-70aded980585</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='purchase_date']</value>
      <webElementGuid>48225184-943b-43e6-9b58-1baeca7bf4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[7]/input</value>
      <webElementGuid>b6881af5-e11f-40e3-bbc3-c59522bef710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>250b0325-1878-4a8e-aa40-fc169cf70e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'purchase_date' and @id = 'purchase_date']</value>
      <webElementGuid>e62db0da-fc83-4fa2-bdd0-49424e1f97b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
