<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Purchase Price_purchase_price</name>
   <tag></tag>
   <elementGuidId>27a0aba8-efc8-4e19-9b8b-1e29eb38145a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#purchase_price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='purchase_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91aff606-a8f0-473e-8e38-094709ac7dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4601cd7c-09e1-4951-922f-2b5d4ccf3425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>purchase_price</value>
      <webElementGuid>787d08ae-c83e-4fdf-a123-733a2bb0f74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchase_price</value>
      <webElementGuid>f16c7579-b2d3-4bf5-83ee-0c386f703025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fb29202a-9df8-4337-87ce-34c1f669bd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter the purchase price</value>
      <webElementGuid>cb9a68e4-f861-4843-a290-5158c6b41d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchase_price&quot;)</value>
      <webElementGuid>e28b3f77-0f2b-435c-a344-7832babf3091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='purchase_price']</value>
      <webElementGuid>bf90472d-4da9-45c2-a515-3120c2627fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[5]/input</value>
      <webElementGuid>a573f1b6-b1b9-49d8-ab33-075fe609f584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>c8bed5b1-2b40-4e5f-b4e1-30904e07925b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'purchase_price' and @id = 'purchase_price' and @placeholder = 'Enter the purchase price']</value>
      <webElementGuid>9c1bde3d-5e25-4dcc-9b2c-226d1c377dae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
