<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Forgot Password_remember-me</name>
   <tag></tag>
   <elementGuidId>8dea6fec-d535-4a1e-8fe5-da0bef3adffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remember-me</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='remember-me']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bba6551a-b551-42d0-b5ac-8f6a7d957c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>67277a5b-1120-4f05-a975-e396d2b66bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>193373b4-092d-4f5d-82c0-8853e24656eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remember-me</value>
      <webElementGuid>3083867e-1366-4091-9752-dfdae683cbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;remember-me&quot;)</value>
      <webElementGuid>a162b62c-5f8f-4eaf-9092-875626b45dd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='remember-me']</value>
      <webElementGuid>89a6bfee-6538-4d94-9627-25614442c7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div/div/form/div[3]/div/input</value>
      <webElementGuid>beba2a34-22e0-42e4-8e74-fddb74605287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>4da59765-c0f8-4912-94bd-91f8d31ea70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'remember-me']</value>
      <webElementGuid>2e6a6162-f7a0-4793-b3ce-cbbf76905adf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
