<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select asset typeComputer EquipmentF_9b6c70</name>
   <tag></tag>
   <elementGuidId>536591f8-0d8d-40e7-b767-3e153708eec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#asset_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='asset_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0f686add-34aa-40c7-9f9a-574be3b23590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>368ccddd-3d45-4b84-b959-17a0e5f441ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asset_type</value>
      <webElementGuid>a7fc0969-f24b-4b1e-ac0e-8083416b63b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>asset_type</value>
      <webElementGuid>a0ec62a3-78ac-4759-9fc1-7f24fd5ab622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select asset typeComputer EquipmentFurniture &amp; FixturesMachineryOffice EquipmentOthersVehicles</value>
      <webElementGuid>36c17f5a-1d3e-4b54-b631-4f66ca4293db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;asset_type&quot;)</value>
      <webElementGuid>20cb9b6b-390e-40a3-a680-79f852b9be1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='asset_type']</value>
      <webElementGuid>3bfe2931-55f4-40c9-84ed-d60032aa3915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[12]/div/select</value>
      <webElementGuid>9fa71bb2-4295-41d8-a490-b86158e00741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Type'])[1]/following::select[1]</value>
      <webElementGuid>a6e31481-67a3-48b2-bca6-97d0a5578998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VI'])[1]/following::select[1]</value>
      <webElementGuid>0e7b4351-6d80-45ae-ba7c-c7613055b24e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next maintenance date'])[1]/preceding::select[1]</value>
      <webElementGuid>e0dd2da1-0094-4211-a212-77f96c1a2d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Status'])[1]/preceding::select[1]</value>
      <webElementGuid>25891420-b804-45b2-8e80-bf42c8cd36b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/select</value>
      <webElementGuid>f86c308e-2198-43bc-a96e-0185aeb0b41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'asset_type' and @id = 'asset_type' and (text() = 'Select asset typeComputer EquipmentFurniture &amp; FixturesMachineryOffice EquipmentOthersVehicles' or . = 'Select asset typeComputer EquipmentFurniture &amp; FixturesMachineryOffice EquipmentOthersVehicles')]</value>
      <webElementGuid>19cb5e3b-1787-4fae-9e92-da77636723c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
