<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please selectAnnuallyBi-WeeklyMonthl_0acacb</name>
   <tag></tag>
   <elementGuidId>ba61898d-be11-4f02-93b8-913404e1e9ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#maintainance_frequency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='maintainance_frequency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3f65e86e-7107-4044-913b-151cba5b5211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>b32de47f-eeea-4f1c-9528-ef029f804b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>maintainance_frequency</value>
      <webElementGuid>41f2443f-33ed-4db6-b921-81395714da7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>maintainance_frequency</value>
      <webElementGuid>8d46ae9b-f672-47ab-b99d-4c8c27b1f962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please selectAnnuallyBi-WeeklyMonthlyQuarterly</value>
      <webElementGuid>b75f89b7-1b70-4596-a07b-3fd780df3f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maintainance_frequency&quot;)</value>
      <webElementGuid>11b106bd-b167-442d-a718-fc2bfdb77e41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='maintainance_frequency']</value>
      <webElementGuid>4d030a6d-4018-4497-802d-a17c234adc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[15]/div/select</value>
      <webElementGuid>cc367379-69f2-4155-9caa-488bbb3e2d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Frequency'])[1]/following::select[1]</value>
      <webElementGuid>697d3a14-6a55-4f3a-92c0-2caf17a1779d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Status'])[1]/following::select[2]</value>
      <webElementGuid>52fe584a-11d4-4ac0-9ecb-04117e7c4f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::select[1]</value>
      <webElementGuid>2b602244-0776-4036-90d0-938eb1f24fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/select</value>
      <webElementGuid>f8b01290-610b-495f-ac08-fc9230c4681c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'maintainance_frequency' and @id = 'maintainance_frequency' and (text() = 'Please selectAnnuallyBi-WeeklyMonthlyQuarterly' or . = 'Please selectAnnuallyBi-WeeklyMonthlyQuarterly')]</value>
      <webElementGuid>e8971739-9ef6-4aa4-b5f5-9939d26d9d36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
