<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select yes if item is insuredNoYes</name>
   <tag></tag>
   <elementGuidId>c555f473-9ba9-4b5b-9a60-f86efc399a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#insurance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='insurance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9b17574d-a06f-4ed7-9c48-8a71cb9b0878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>2a90c9c0-4298-4e30-b344-4d32b98cccf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insurance</value>
      <webElementGuid>961a63f4-2aff-46c2-a00c-cb350ec3d67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insurance</value>
      <webElementGuid>090a0971-5f06-408b-988f-30a65eebb720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ‘yes’ if item is insuredNoYes</value>
      <webElementGuid>6702a3cc-b61f-45ca-ab49-3424a1610d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance&quot;)</value>
      <webElementGuid>c612af0d-eb10-4578-aad0-50793b23a617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='insurance']</value>
      <webElementGuid>bb59dec2-b590-4c2f-815c-4407b8e948ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[10]/div/select</value>
      <webElementGuid>46e249ce-f20b-4163-ae56-a664ca720c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insured'])[1]/following::select[1]</value>
      <webElementGuid>1ee9c1b0-1051-4582-8c49-64d3b49b1a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laptop'])[1]/following::select[1]</value>
      <webElementGuid>98a201c7-7e49-471b-9dcd-cc79fa648475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/preceding::select[1]</value>
      <webElementGuid>51f6b421-aa28-4c8e-9364-8ecf7e2aa9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select...'])[1]/preceding::select[1]</value>
      <webElementGuid>bc71e755-2844-4d61-be2f-700cf21829a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/select</value>
      <webElementGuid>d2b2ce87-8b34-4381-bf0b-70901f88911b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'insurance' and @id = 'insurance' and (text() = 'Select ‘yes’ if item is insuredNoYes' or . = 'Select ‘yes’ if item is insuredNoYes')]</value>
      <webElementGuid>968bac3a-b28a-4b01-b8b1-6cc8a66df246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
