<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select currencyADB Unit Of Ac_37609f</name>
   <tag></tag>
   <elementGuidId>004e03bd-cf21-47ad-b026-34949c3826d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='currency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d6f71b5d-4e2f-406d-919e-f28e672fb211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>32bfe007-7739-44fc-8156-ed225922e158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>c71b8f62-f43f-4356-8497-de03aeb95e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currency</value>
      <webElementGuid>bcdfe35e-83ed-494f-ad96-08feb39af2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select currencyADB Unit Of AccountAfghaniAlgerian DinarArgentine PesoArmenian DramAruban FlorinAustralian DollarAzerbaijan ManatBahamian DollarBahraini DinarBahtBalboaBarbados DollarBelarusian RubleBelize DollarBermudian DollarBolivianoBolívar SoberanoBond Markets Unit European Composite Unit (EURCO)Bond Markets Unit European Monetary Unit (E.M.U.-6)Bond Markets Unit European Unit Of Account 17 (E.U.A.-17)Bond Markets Unit European Unit Of Account 9 (E.U.A.-9)Brazilian RealBrunei DollarBulgarian LevBurundi FrancCabo Verde EscudoCanadian DollarCayman Islands DollarCFA Franc BCEAOCFA Franc BEACCFP FrancChilean PesoCodes Specifically Reserved For Testing PurposesColombian PesoComorian Franc Congolese FrancConvertible MarkCordoba OroCosta Rican ColonCuban PesoCzech KorunaDalasiDanish KroneDenarDjibouti FrancDobraDominican PesoDongEast Caribbean DollarEgyptian PoundEl Salvador ColonEthiopian BirrEuroFalkland Islands PoundFiji DollarForintGhana CediGibraltar PoundGoldGourdeGuaraniGuinean FrancGuyana DollarHong Kong DollarHryvniaIceland KronaIndian RupeeIranian RialIraqi DinarJamaican DollarJordanian DinarKenyan ShillingKinaKunaKuwaiti DinarKwanzaKyatLao KipLariLebanese PoundLekLempiraLeoneLiberian DollarLibyan DinarLilangeniLotiMalagasy AriaryMalawi KwachaMalaysian RinggitMauritius RupeeMexican PesoMexican Unidad De Inversion (UDI)Moldovan LeuMoroccan DirhamMozambique MeticalMvdolNairaNakfaNamibia DollarNepalese RupeeNetherlands Antillean GuilderNew Israeli SheqelNew Taiwan DollarNew Zealand DollarNgultrumNorth Korean WonNorwegian KroneOuguiyaPakistan RupeePalladiumPatacaPa’angaPeso ConvertiblePeso UruguayoPhilippine PesoPlatinumPound SterlingPulaQatari RialQuetzalRandRial OmaniRielRomanian LeuRufiyaaRupiahRussian RubleRwanda FrancSaint Helena PoundSaudi RiyalSDR (Special Drawing Right)Serbian DinarSeychelles RupeeSilverSingapore DollarSolSolomon Islands DollarSomSomali ShillingSomoniSouth Sudanese PoundSri Lanka RupeeSucreSudanese PoundSurinam DollarSwedish KronaSwiss FrancSyrian PoundTakaTalaTanzanian ShillingTengeThe Codes Assigned For Transactions Where No Currency Is InvolvedTrinidad And Tobago DollarTugrikTunisian DinarTurkish LiraTurkmenistan New ManatUAE DirhamUganda ShillingUnidad De FomentoUnidad De Valor RealUnidad PrevisionalUruguay Peso En Unidades Indexadas (UI)US DollarUS Dollar (Next Day)Uzbekistan SumVatuWIR EuroWIR FrancWonYemeni RialYenYuan RenminbiZambian KwachaZimbabwe DollarZloty</value>
      <webElementGuid>573478ed-282c-4cf0-98c8-940e5595452b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currency&quot;)</value>
      <webElementGuid>0c124a22-2679-45fe-942e-8f3fb8ef2b14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='currency']</value>
      <webElementGuid>75941c5c-ab41-43a3-a2c6-1356e9ffc218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[6]/div/select</value>
      <webElementGuid>98f85955-c51a-4631-b72e-9f276c20aa3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/following::select[1]</value>
      <webElementGuid>b922132b-a359-4455-84fe-3e9d2a875efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Price'])[1]/following::select[1]</value>
      <webElementGuid>0efcc340-83ce-4556-b05f-fdd8768607de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Date'])[1]/preceding::select[1]</value>
      <webElementGuid>e8e972ef-1923-4386-8288-563b4903f7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor'])[1]/preceding::select[1]</value>
      <webElementGuid>3d160449-0e7e-47af-b934-3a9497708119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c9ba504d-2628-488b-92a3-59148c275e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency' and @id = 'currency' and (text() = 'Please select currencyADB Unit Of AccountAfghaniAlgerian DinarArgentine PesoArmenian DramAruban FlorinAustralian DollarAzerbaijan ManatBahamian DollarBahraini DinarBahtBalboaBarbados DollarBelarusian RubleBelize DollarBermudian DollarBolivianoBolívar SoberanoBond Markets Unit European Composite Unit (EURCO)Bond Markets Unit European Monetary Unit (E.M.U.-6)Bond Markets Unit European Unit Of Account 17 (E.U.A.-17)Bond Markets Unit European Unit Of Account 9 (E.U.A.-9)Brazilian RealBrunei DollarBulgarian LevBurundi FrancCabo Verde EscudoCanadian DollarCayman Islands DollarCFA Franc BCEAOCFA Franc BEACCFP FrancChilean PesoCodes Specifically Reserved For Testing PurposesColombian PesoComorian Franc Congolese FrancConvertible MarkCordoba OroCosta Rican ColonCuban PesoCzech KorunaDalasiDanish KroneDenarDjibouti FrancDobraDominican PesoDongEast Caribbean DollarEgyptian PoundEl Salvador ColonEthiopian BirrEuroFalkland Islands PoundFiji DollarForintGhana CediGibraltar PoundGoldGourdeGuaraniGuinean FrancGuyana DollarHong Kong DollarHryvniaIceland KronaIndian RupeeIranian RialIraqi DinarJamaican DollarJordanian DinarKenyan ShillingKinaKunaKuwaiti DinarKwanzaKyatLao KipLariLebanese PoundLekLempiraLeoneLiberian DollarLibyan DinarLilangeniLotiMalagasy AriaryMalawi KwachaMalaysian RinggitMauritius RupeeMexican PesoMexican Unidad De Inversion (UDI)Moldovan LeuMoroccan DirhamMozambique MeticalMvdolNairaNakfaNamibia DollarNepalese RupeeNetherlands Antillean GuilderNew Israeli SheqelNew Taiwan DollarNew Zealand DollarNgultrumNorth Korean WonNorwegian KroneOuguiyaPakistan RupeePalladiumPatacaPa’angaPeso ConvertiblePeso UruguayoPhilippine PesoPlatinumPound SterlingPulaQatari RialQuetzalRandRial OmaniRielRomanian LeuRufiyaaRupiahRussian RubleRwanda FrancSaint Helena PoundSaudi RiyalSDR (Special Drawing Right)Serbian DinarSeychelles RupeeSilverSingapore DollarSolSolomon Islands DollarSomSomali ShillingSomoniSouth Sudanese PoundSri Lanka RupeeSucreSudanese PoundSurinam DollarSwedish KronaSwiss FrancSyrian PoundTakaTalaTanzanian ShillingTengeThe Codes Assigned For Transactions Where No Currency Is InvolvedTrinidad And Tobago DollarTugrikTunisian DinarTurkish LiraTurkmenistan New ManatUAE DirhamUganda ShillingUnidad De FomentoUnidad De Valor RealUnidad PrevisionalUruguay Peso En Unidades Indexadas (UI)US DollarUS Dollar (Next Day)Uzbekistan SumVatuWIR EuroWIR FrancWonYemeni RialYenYuan RenminbiZambian KwachaZimbabwe DollarZloty' or . = 'Please select currencyADB Unit Of AccountAfghaniAlgerian DinarArgentine PesoArmenian DramAruban FlorinAustralian DollarAzerbaijan ManatBahamian DollarBahraini DinarBahtBalboaBarbados DollarBelarusian RubleBelize DollarBermudian DollarBolivianoBolívar SoberanoBond Markets Unit European Composite Unit (EURCO)Bond Markets Unit European Monetary Unit (E.M.U.-6)Bond Markets Unit European Unit Of Account 17 (E.U.A.-17)Bond Markets Unit European Unit Of Account 9 (E.U.A.-9)Brazilian RealBrunei DollarBulgarian LevBurundi FrancCabo Verde EscudoCanadian DollarCayman Islands DollarCFA Franc BCEAOCFA Franc BEACCFP FrancChilean PesoCodes Specifically Reserved For Testing PurposesColombian PesoComorian Franc Congolese FrancConvertible MarkCordoba OroCosta Rican ColonCuban PesoCzech KorunaDalasiDanish KroneDenarDjibouti FrancDobraDominican PesoDongEast Caribbean DollarEgyptian PoundEl Salvador ColonEthiopian BirrEuroFalkland Islands PoundFiji DollarForintGhana CediGibraltar PoundGoldGourdeGuaraniGuinean FrancGuyana DollarHong Kong DollarHryvniaIceland KronaIndian RupeeIranian RialIraqi DinarJamaican DollarJordanian DinarKenyan ShillingKinaKunaKuwaiti DinarKwanzaKyatLao KipLariLebanese PoundLekLempiraLeoneLiberian DollarLibyan DinarLilangeniLotiMalagasy AriaryMalawi KwachaMalaysian RinggitMauritius RupeeMexican PesoMexican Unidad De Inversion (UDI)Moldovan LeuMoroccan DirhamMozambique MeticalMvdolNairaNakfaNamibia DollarNepalese RupeeNetherlands Antillean GuilderNew Israeli SheqelNew Taiwan DollarNew Zealand DollarNgultrumNorth Korean WonNorwegian KroneOuguiyaPakistan RupeePalladiumPatacaPa’angaPeso ConvertiblePeso UruguayoPhilippine PesoPlatinumPound SterlingPulaQatari RialQuetzalRandRial OmaniRielRomanian LeuRufiyaaRupiahRussian RubleRwanda FrancSaint Helena PoundSaudi RiyalSDR (Special Drawing Right)Serbian DinarSeychelles RupeeSilverSingapore DollarSolSolomon Islands DollarSomSomali ShillingSomoniSouth Sudanese PoundSri Lanka RupeeSucreSudanese PoundSurinam DollarSwedish KronaSwiss FrancSyrian PoundTakaTalaTanzanian ShillingTengeThe Codes Assigned For Transactions Where No Currency Is InvolvedTrinidad And Tobago DollarTugrikTunisian DinarTurkish LiraTurkmenistan New ManatUAE DirhamUganda ShillingUnidad De FomentoUnidad De Valor RealUnidad PrevisionalUruguay Peso En Unidades Indexadas (UI)US DollarUS Dollar (Next Day)Uzbekistan SumVatuWIR EuroWIR FrancWonYemeni RialYenYuan RenminbiZambian KwachaZimbabwe DollarZloty')]</value>
      <webElementGuid>a765ce15-10af-4510-890b-2c0a4673a5a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
