<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select asset statusDefectiveWorking _559757</name>
   <tag></tag>
   <elementGuidId>297c7bf4-251e-41e8-b438-63617caed82a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#condition</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='condition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d34791b2-15cd-47e2-a3ca-4ea71d319a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>5289fd69-5ec6-4438-846d-9f24a0ba9abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>condition</value>
      <webElementGuid>dd6e7181-7857-47b2-ab0c-52d0cffd624f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>condition</value>
      <webElementGuid>a2bcfdf2-7864-464e-89eb-2baf1aa992a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select asset statusDefectiveWorking Perfectly</value>
      <webElementGuid>d4f5675e-3f38-4419-95a8-ad2eef6b2eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;condition&quot;)</value>
      <webElementGuid>288692a9-61a4-4472-8181-99d0e9ad40ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='condition']</value>
      <webElementGuid>d2540cea-f737-4bed-a6ea-8796f56c98e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div/div/div/div[2]/form/div/div[14]/div/select</value>
      <webElementGuid>2e7b7c92-47f5-4c17-99a0-b87e54f5676d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset Status'])[1]/following::select[1]</value>
      <webElementGuid>0d60b876-da0c-4baa-a07f-b9e9a0ba6640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next maintenance date'])[1]/following::select[1]</value>
      <webElementGuid>823d7b1a-075a-4e1a-b369-d983812eb2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance Frequency'])[1]/preceding::select[1]</value>
      <webElementGuid>4dfd66fd-5402-4795-b2b5-1f138215f96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/select</value>
      <webElementGuid>1ce132de-5bbc-4c50-adbf-8bdf41e56af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'condition' and @id = 'condition' and (text() = 'Select asset statusDefectiveWorking Perfectly' or . = 'Select asset statusDefectiveWorking Perfectly')]</value>
      <webElementGuid>b621c68b-12aa-4552-81e1-a90bef0e781a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
